### ISSUE TITLE
Current status of the skin

### ISSUE THREAD

**Issue by mistervee** [mistervee/skin.madnox#44]
@bartolomesoriano @gibxxi @meowmoo @Slipass 

An update....
The skin is 90% for an alpha release, i am determined to have it ready for the forums by ~~Christmas~~ sometime in the future.

What needs to be finished....

Code Optimization
- In progress
- ~~Clean up and rearrange the includes and variables~~

Skin functions that are not complete
- ~~Now Playing - Home screen, Fullscreen music and video~~
- ~~Skin backgrounds~~
- ~~Information dialogs recode and support for TheMovieDb helper and Embuary info (partially done for videos) Done, removed online support, maybe add it back at a later time.~~
- ~~Fallback artwork for library views~~
- ~~Kodi Profile selection~~
- ~~Code Embuary Info Actors/Videos xml's~~
- ~~Code Next Aired xml~~
- ~~Code RSS editor and add to optional addons~~
- ~~Code UP Next addon and add to optional addons~~
- ~~Watched flags for widgets and library views~~

Other
- ~~Review feature requests and bug reports on github in "issues"~~
- Fix Kodi log warning/errors
- ~~Add search options using dynamic content~~

If there is anything you think i have left out please let me know.

I really appreciate your help. TY all.
Cheers
Mr. V

**Comment by meowmoo** [comment]
Can I request tmdb rating in the video info screen? It seems that it is used in, example, list view, but not in the video info 
http://imgur.com/a/URjV3f3

Also as you can see in the picture the poster is a bit cut of, the A and N.

**Comment by mistervee** [comment]
@djp952 

Thanks for the help. 

I spent a few hours on this and could not get it working. I did learn a lot on how to set it up, really just some more trial and error to make it work (as you said) and i am sure i can get it sorted.

For now it will be download of the whole skin as i do not want to be concerend with version numbers or change logs.

Cheers
Mr. V

**Comment by mistervee** [comment]
@gibxxi @bartolomesoriano @meowmoo @Slipass 

I have deleted some commnets in this thread related to my medical issues.

**Comment by mistervee** [comment]
@meowmoo

> @mistervee Can I request tmdb rating in the video info screen?
> http://imgur.com/a/URjV3f3
> Trakt rating would be cool also, but since it get not pulled in to the db from the scanner it is not easy/possible at all?
> 
> Also as you can see in the picture the poster is a bit cut of, the A and N.

TMDb ratings added
Fixed the poster with the edges being cut off.

I wont be be adding trakt ratings as that info is not availble in the kodi database.

**Comment by mistervee** [comment]
@gibxxi @bartolomesoriano @meowmoo @Slipass 

Final update on git before alpha release.
- Removed variables not used
- Removed includes not used
- Removed fonts not used
- Add missing language strings
- Clean up of xml's

Conversation can be continued in;
https://github.com/mistervee/skin.madnox/issues/45


Cheers and thankyou all
Mr. V


This thread will be closed.
