### ISSUE TITLE
To do list - Leia

### ISSUE THREAD

**Issue by mistervee** [mistervee/skin.madnox#45]
- ~~Review all xml files~~
- ~~Check for kodi log warning/errors~~
- ~~Update next aired info for tmdb addon~~
- ~~Fix alignment of rightlist view labels~~ only one report and cant reproduce
- ~~Mediamenu/options for dynamic search~~ not adding menu
- Create repo for skin  - after release to repo
- ~~Option to override video info with embuary info~~ Noop, may change to TMDb helper for matrix
- ~~Override video info with embuary info for when user presses info button on widget or addon~~ Noop, may change to TMDb helper for matrix
- ~~Enable use of mouse to scroll for next widget~~
- ~~kodiflix view and other views - scrollbar skips past an item due to the co-ordindinates being off screen~~ same issue with estuary, will have to redesign view if needed. not happening
- ~~fallback artwork for landscape images~~
- ~~Seperate option for music OSD background textures~~
- ~~Blur background - find a way to speed up loading~~ (Look at TMDb helper when updating matrix)
- ~~Add 4x12 wall poster view~~ added option for small posters 3.5x10 layout as 4x12 looked to small
- ~~Add option to adjust background transparency for kodiflix rightlist ect.~~ - 
- ~~Add options in misc. views for labels for artist and episode content~~
- ~~Enable additional landscape views for episodes~~
- ~~Review scale vs stretch for all images in skin~~ fix at user request.
- ~~Add <background>0</background to all windows and update variables to remove black screen when chaning windows~~ - matrix
- ~~Improve animations~~ - matrix

**Comment by bartolomesoriano** [comment]
@mistervee , I don't know if what I have is too simple for what you are looking for, but I have a repo for Amber and it works well.  If you want, take a look at it on GitHub, and I can post here the batch file that I use to update it.

**Comment by meowmoo** [comment]
Since the last update, the infoline and the now playing info are overlapping on the home screen

**Comment by mistervee** [comment]
@meowmoo 
Thanks for the bug report. Should be fixed.

**Comment by meowmoo** [comment]
@mistervee thanks for the fix.

Actors load instantly now, thanks
I would recommend to use the stretch setting on all views, my alien posters all get cut of

**Comment by mistervee** [comment]
@meowmoo 
Ok. Fair point. Posters have changed to stretch. Think i got them all. Let me know if i have missed anything.

**Comment by meowmoo** [comment]
@mistervee looks good on my end, thank you.

In the right list view options, the 3 option "show CD art" don't have a label. Also on right list, when you turn logo on, it shows at the top right and bottom right overlying the cover.

Maby it's just me or my setup but the videoinfo fade out animation looks nicer than the fade in.

Fade in is almost instantly, like the info ist popping up. 
Fade out is clearly slowly fading out. 
Or is this on purpose? 

Here is a video I captured. 
https://drive.google.com/file/d/1IbKLRwEZv1GdeLd9e6gHVmbUiXVQ_nrP/view?usp=drivesdk

**Comment by mistervee** [comment]
@meowmoo
 
Disc art label is fixed.

In the video I notice a slight delay in the loading of the actor thumbs. My dev pc is amd 3600 and 5700xt. I have no delay. When I press info, it is instant. 

Using my slow android tv I see the same behaviour you have mentioned only on the first load of the info screen. Second time animation seems ok.

I have increased the fade time for the video info animation, it should show some improvement.

Let me know if it works for you. If not I will post a video for comparison.

**Comment by meowmoo** [comment]
To be honest I don't see any difference on my setup, vero4k+,
I would have never noticed it in first place if you haven't put it in the change log, so I was paying extra attention to that animation. All fine on my side. 

If you change the 'cover background' setting for the submenu background, I. E background, sorting, the new setting label and the standard label are overlapping.

When you press up on a actor to see the movies, they are totally random sortet, sort them by year would be a logical order, same go's für music artist discography in the music info. 

Not sure if it's my fault or only me, but when you press up on a actor to see the movies I don't get the posters anymore it looks like a thumbnail

**Comment by mistervee** [comment]
@meowmoo 

Thanks found the bugs.
- Fixed submenu coverbackground overlaping of labels
- Actor movies, albums, similar, director ect is now sorted by year
- Changed video info to use poster instead of thumbs

The only one left is the animation, and i think it related to the performance of the device and/or network performance. When opening the video info the skin is loading 7 or more containers and artwork. My guess is the animations are not rendered due to the overhead. So the cpu/gpu can not keep up.
  
Can you try disabling the sets, director, writer, similar button, blur background and cdart. Also enable TMDb actor info. That will reduce the overhead when opening the info screen. It is not ideal, but i am thinking i made need to recode and redesign the info dialogs. Skins like Aeon nox silvo, Artic Horizon are coded differently and i assume this is not an issue with these skins.

The other thing i have not coded is a limit on the number of items for each container. If you have a large library, things will slow down further.

**Comment by Slipass** [comment]
@mistervee 

I found a few Bugs and a suggestion for features:

1: If I go to the film view (Coverflow) and have a film collection there and then switch to the series (Lowlist), I see the film collection as background
[https://i.imgur.com/KyV4B1U.jpg](url)

2: If I have selected the 4 frames view for the movies (Coverflow) and Video Preview is enabled, the 4 frames are not displayed.
[https://i.imgur.com/Xap6HoJ.jpg](url)

Here an example from the old Kodi Version
[https://i.imgur.com/xva1YZj.jpg](url)

3: Is it possible to display the thumbs instead of the cover in the third level of the lowlist view?
[https://i.imgur.com/3C1J1xb.jpg](url)

Here an example from the old Kodi Version
[https://i.imgur.com/ckYB6q2.jpg](url)

4: Feature suggestion: Is it possible to show the percentage for the status (seen/unseen)?
[https://i.imgur.com/EMJBbRx.jpg](url)

Thanks and have a nice weekend

**Comment by gibxxi** [comment]
I've also got one to report.

In episode view for a TV show, if you watch a bunch of episodes from a show (concurrently) then drop back to the episode list view from the episode you just had playing, the watched status (checkmark) is not displayed on the episodes you just watched. 

However, if you drop back to season view, then re-enter episode view, the list is then updated correctly. This implies to me that an update is not being performed by the skin upon successful watching of each episode / at the point you stop playing and drop back to the skin / UI. Not sure if this can be fixed, and is a minor gripe, but noticed it nonetheless.

Regards,

Dan / Gib.

**Comment by mistervee** [comment]
@meowmoo 
In regards to the animation and the video info, You could possibly speed up the GUI by changing the 'dirty regions' in the advanced settings.
https://kodi.wiki/view/Advancedsettings.xml#algorithmdirtyregions

@gibxxi @Slipass 
I will get back to you.

**Comment by meowmoo** [comment]
@mistervee thanks for the link, I will give it a try, but to be honest, I would have never noticed it in first place if you haven't put it in the change log, so I was super focused on the animation and noticed the "lag". It don't bother me at all! All good on my end! 

One more bug to report, on 3 panel view you can't navigate to the letter bar on the right side, it stops on the description dot.

**Comment by mistervee** [comment]
@gibxxi 
Tried to replicate, the issue you are having with the media flags. From my end everything seems to be working and cannot see any issue with the code. Using Kodi v18.8.

The variable used should update when the video has ended, being the info label 'ListItem.Overlay';
`<value condition="ListItem.IsPlaying">overlays/list/OverlayPlay.png</value>`
`<value condition="ListItem.IsResumable">overlays/list/OverlayResume.png</value>`
`<value condition="Container.Content(seasons) + !ListItem.IsParentFolder + !String.IsEqual(ListItem.Property(WatchedEpisodes),ListItem.Property(TotalEpisodes))">overlays/list/OverlayUnWatched.png</value>`
`<value condition="Container.Content(seasons) + !ListItem.IsParentFolder + String.IsEqual(ListItem.Property(WatchedEpisodes),ListItem.Property(TotalEpisodes))">overlays/list/OverlayWatched.png</value>`
`<value condition="!String.IsEmpty(ListItem.Overlay)">overlays/list/$INFO[ListItem.Overlay]</value>`

I am not sure why this would be happening. May be something to do with the variable?

@meowmoo 
Thanks. Fixed for the music 3 panel view. 

@Slipass 
Still deciding on what updates i will and will not do.

**Comment by gibxxi** [comment]
@mistervee 

I can't really provide screenshots because it's a static issue. I had a series I was watching (Castle - S05), I played 4 episodes using the NextUP addon, back-to-back. At the end of the 4th episode I manually stopped playback, and Kodi returned to the episode list (Right-list view), but none of the episodes that had been watched showed "Watched" icons, all still showed "Unwatched" icons. 

I thought it strange, so stepped back one step to the season view, then re-entered episode view and the status had then been updated to reflect those episodes had been watched. Maybe it's something to do with the way NextUP / UpNext (whatever the damn thing is calling itself now, lol) is doing something, with regards the video database watched status.

I have it trigger it's pop-up for playback of the next episode, 30 seconds from the end of playback from the playing episode, so at that stage perhaps it's not sending a "watched" marker for those episoodes until after you've already manually stopped playback, I don't know.

It's a minor issue, so not worth dedicating much time to.

Dan / Gib.

**Comment by mistervee** [comment]
@gibxxi 

Thanks for the extra info.

I have not spent much time on this just tried to do the same steps you mentioned. Only a few minutes of testing and checking the code.

From a technical point (what i have read in the forums), Visibility conditions are updated every frame. The watched status is a variable so it should immediatly update. No matter what i do a cannot replicate the issue, it might be specific to your kodi install.

If you want me to figure out why it is not working i will need a debug log. Should not take long to see if it is an addon or database issue.

**Comment by gibxxi** [comment]
@mistervee 

OK. Next time I get thew opportunity to do a binge-watching session, I'll get a debug log for you (assuming the issue occurs again).

Dan / Gib.
