### ISSUE TITLE
Cover playlist backgrounds not working properly

### ISSUE THREAD

**Issue by Fietspomp86** [mistervee/skin.madnox#46]
First of all, really love and admire the dedication put in this skin. 

I've just installed it today and ran into an issue, hope it's ok to raise it here.
Found it was also mentioned on the Kodi forum.

When selecting a Cover playlist background for the main menu, it is not showing up.
It is only showing up when going to the submenu of that category (arrow down).

I'm using the skin on the latest Libreelec x64.

[Here's a link from the forum with pictures](https://forum.kodi.tv/showthread.php?tid=325359&pid=2975116#pid2975116)

**Comment by mistervee** [comment]
@Fietspomp86 
Should be fixed with latest update.

**Comment by Fietspomp86** [comment]
@mistervee 

Works properly after the lastest update!
Thanks.
