### ISSUE TITLE
Font13 missing in font.xml (For Picture Slideshow Screensaver)

### ISSUE THREAD

**Issue by Fietspomp86** [mistervee/skin.madnox#48]
Found a small bug where the text was missing in the Picture Slideshow Screensaver.

Apparently this is because "font13" is missing in Font.xml
Tried adding this piece of code:

```
		<font>
			<name>font13</name>
			<filename>OpenSansCond.ttf</filename>
			<size>31</size>
		</font>
```

Into Font.xml, this makes it work.

Probably a dirty fix and I'm not sure if it breaks anything else, hence I didn't make a PR.

**Comment by mistervee** [comment]
@Fietspomp86 
Thanks. font13 added.
