### ISSUE TITLE
Addons Disable and Enable with the same name

### ISSUE THREAD

**Issue by Kampfader** [mistervee/skin.madnox#49]
see the pic 

Addon Enable
![image](https://user-images.githubusercontent.com/23200748/94967415-4ffbb680-04ff-11eb-87cf-6d1832e04f92.png)

Addon is Disabled
![image](https://user-images.githubusercontent.com/23200748/94967438-60ac2c80-04ff-11eb-813b-5aa2a202060c.png)

**Comment by mistervee** [comment]
@Kampfader 
Thanks. Fixed.

**Comment by Kampfader** [comment]
Works, thanks..
